### ISSUE TITLE
Modal doesn't close when pressing Escape

### ISSUE THREAD

**Issue by danialdezfouli** [Frontify/fondue#1444]
fondue doesn't call onClose when pressing Escape.
the modal remains in the dom and only changes the opacity to 0.

<img width="1439" alt="image" src="https://github.com/Frontify/fondue/assets/12775482/412aa592-fda6-4209-9eaa-f85948430706">

```json
"@frontify/fondue": "12.0.0-beta.227"
```

**Comment by danialdezfouli** [comment]
I had to do this for closing it:
```tsx
  useLayoutEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape' && isOpen) {
        onClose()
      }
    }
    window.addEventListener('keydown', handleKeyDown, true)
    return () => {
      window.removeEventListener('keydown', handleKeyDown, true)
    }
  }, [isOpen, onClose])
```

**Comment by imoutaharik** [comment]
Hello! First, thanks for using Fondue :) and for the feedback.
We're currently working on the refactoring of our overlays including the `Modal` which will be deprecated and replaced by the new `Dialog` component. It's still a work in progress.
Part of the work, I already introduced a new hook here: https://github.com/Frontify/fondue/blob/beta/src/hooks/useToggleOverlay.ts
That is already listening to the escape key.
```const [isOpen, setIsOpen] = useToggleOverlay(false);```
Hopefully those new components should be ready on beta within next month.

**Comment by SamuelAlev** [comment]
Fixed with the new `Dialog` component
