### ISSUE TITLE
Popper: Missing PopperPlacement types

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#1475]
Seems as if they aren’t exported?
https://github.com/Frontify/fondue/blob/beta/src/components/Popper/Popper.tsx

```export 'PopperPlacement' (imported as 'PopperPlacement') was not found in '@frontify/fondue'```

**Comment by imoutaharik** [comment]
Sorry about that, the export is missing in index.ts. 🙈 I will fix ASAP
