### ISSUE TITLE
Button: Title, tooltip, aria-label?

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#769]
**Goal:** 
I want to decorate a `<Button>` component (with `icon` prop) with a tooltip. A native `title` would be fine, a `<Tooltip>` even better. Are there any examples for that? 

Something like that:

<img width="170" alt="image" src="https://user-images.githubusercontent.com/183989/166919452-ef53ba1a-e4bf-492f-8241-9efe39ea491c.png">

**Problem:**
I’d like to add a `title` attribute to a `<Button>`, but there’s no prop and other attributes aren’t merged. There’s `aria-label`, but this won’t show a little native tooltip when hovering over the button. A `tooltip` prop would be handy, but composition would work too. :)

**Comment by thisguyscode** [comment]
@getflourish Yeah this is absolutely valid. I think we should do as you say and add the `tooltip: <Tooltip/>` property to the `Button`

@imoutaharik Would this be an easy addition once the new tooltip is out or something for the backlog (or for me to do)?

**Comment by imoutaharik** [comment]
@thisguyscode I don't think that adding a prop as `tooltip: <Tooltip/>` will work. With the new version of tooltip you need to pass the button trigger to the component like this `<Tooltip triggerElement={<Button>I'm a trigger</Button>} />. Maybe passing the tooltip props but we'll need to check how everything behaves when there is an onClick on the button.

**Comment by getflourish** [comment]
@imoutaharik @thisguyscode Okay, so the new Tooltip will behave similar to a `Flyout` which also uses a `trigger` prop. I think I could work with that :)
