### ISSUE TITLE
Badge: Alignment of Icons

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#797]
When using Badges with Icons, the vertical alignment of the icons could be improved. Right now, the icons are hanging too low. Could be fixed by changing the styles of the span that wraps the SVG :)

https://github.com/Frontify/arcade/blob/main/src/components/Badge/Badge.tsx#L66

<img width="42" alt="image" src="https://user-images.githubusercontent.com/183989/168538779-798d6ffe-8996-417d-b872-cf64739d52dd.png">

<img width="35" alt="image" src="https://user-images.githubusercontent.com/183989/168538800-6311ccf6-1710-4cd8-ae56-a780e7a4b25a.png">

<img width="52" alt="image" src="https://user-images.githubusercontent.com/183989/168539112-593af279-827f-43ee-b1de-e232851ff5d2.png">

**Comment by julianiff** [comment]
Found it in Safari under this URL: https://fondue-components.frontify.com/?path=/story/components-badge--with-icon
<img width="642" alt="Screenshot 2022-07-27 at 09 12 26" src="https://user-images.githubusercontent.com/14964896/181184721-36f0be59-7beb-436d-a591-c837ca767f67.png">

**Comment by julianiff** [comment]
Fixed with setting line-height to 1 to center image in safari

![Screenshot 2022-07-27 at 14 54 36](https://user-images.githubusercontent.com/14964896/181251778-c5a1a990-060d-4d61-9c16-6cc9a0f4e091.png)

**Comment by getflourish** [comment]
Thanks @julianiff #details-matter
