### ISSUE TITLE
Button: Rounding

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#877]
I think it would make sense if the "rounding" prop of a "Button" that only has an "Icon" would result in a circular button. Right now it’s more like an oval. 

https://fondue-components.frontify.com/?path=/story/components-button--with-icon&args=rounding:Full

<img width="96" alt="image" src="https://user-images.githubusercontent.com/183989/178935321-901f5bbf-8979-45dd-b220-b28dc7297a3c.png">

**Comment by jonasbuechel** [comment]
Issue is reproducible on Safari

**Comment by julianiff** [comment]
Resolved with re-design of buttons. (added line-height: 1 to icons to keep centering also in safari) #857 feat/button-styles-main-merge

**Comment by getflourish** [comment]
Nice! 🙌
